name: sentiment_dashboard
channels:
  #- conda-forge
  #- huggingface
  - anaconda
dependencies:
  - python=3.9
  - pip
  - transformers
  - pip:
      - yfinance  
      - streamlit
      - celery[redis]
      - dash
      - pymysql 
      - sqlalchemy 
      - beautifulsoup4 
      - requests
      - alembic

# prefix: /Users/tobias/miniforge3/envs/sentiment_dashboard
