"""Initial Version

Revision ID: 3ce4d16587b7
Revises: 
Create Date: 2022-11-01 14:48:52.138692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ce4d16587b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticker_org')
    op.alter_column('ticker', 'headline',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('ticker', 'source',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ticker', 'sentiment',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('ticker', 'score',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticker', 'score',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('ticker', 'sentiment',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('ticker', 'source',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ticker', 'headline',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.create_table('ticker_org',
    sa.Column('date', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('datetime', mysql.DATETIME(), nullable=True),
    sa.Column('headline', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('link', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('source', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('text', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('stock_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sentiment', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.symbol'], name='ticker_org_ibfk_1'),
    sa.PrimaryKeyConstraint('link'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
